
stages:
 - build
 - test

cache:
 paths:
   - .m2/repository
 key: "$CI_JOB_NAME"

build_job:
  stage: build
  image: maven:3.8-openjdk-17
  script: "mvn compile -B"


test_job:
  stage: test
  image: maven:3.8-openjdk-17
  script: "mvn test -B"


