image: maven:3.8-openjdk-17

stages:
  - prepare
  - test
  - build
  - info

prepare:
  stage: prepare
  script:
    - echo "Préparation de l'environnement"

test:
  stage: test
  script:
    - echo "Exécution des tests"
    - mvn test

build:
  stage: build
  script:
    - echo "Construction du projet"
      - mvn clean package
      - mkdir -p TourGuide/libs
      - mv target/tourguide-0.0.1-SNAPSHOT.jar TourGuide/libs/ || echo "Aucun JAR à déplacer"
      - ls TourGuide/libs/  # Débogage
  artifacts:
    paths:
      - TourGuide/libs/*.jar


get_jar_info:
  stage: info
  script:
    - |
      if ls TourGuide/libs/*.jar >/dev/null 2>&1; then
        for JAR_FILE in TourGuide/libs/*.jar; do
          echo "Fichier JAR: $JAR_FILE"
          jar tf "$JAR_FILE"
          unzip -p "$JAR_FILE" META-INF/MANIFEST.MF | grep "Implementation-Version" || echo "Aucun manifeste pour $JAR_FILE"
        done
      else
        echo "Erreur : Aucun JAR trouvé dans TourGuide/libs/"
      fi