image: maven:3.8-openjdk-17

stages:
  - prepare
  - test
  - build

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  MAVEN_CLI_OPTS: "-B -ntp"

prepare-job:
  stage: prepare
  script:
    - cd project-tour-guide/TourGuide
    - echo "Installation des .jar locaux dans le repo Maven"
    - for jar in libs/*.jar; do
      name=$(basename "$jar" .jar);
      mvn install:install-file \
      -Dfile=$jar \
      -DgroupId=$name \
      -DartifactId=$name \
      -Dversion=1.0 \
      -Dpackaging=jar \
      -DgeneratePom=true \
      $MAVEN_CLI_OPTS;
      done
  artifacts:
    paths:
      - .m2/repository
    expire_in: 1 hour

test-job:
  stage: test
  dependencies:
    - prepare-job
  script:
    - cd project-tour-guide/TourGuide
    - echo "Lancement des tests unitaires"
    - mvn test $MAVEN_CLI_OPTS
  artifacts:
    reports:
      junit: target/surefire-reports/TEST-*.xml

build-job:
  stage: build
  dependencies:
    - test-job
  script:
    - cd project-tour-guide/TourGuide
    - echo "Build final avec package"
    - mvn package $MAVEN_CLI_OPTS
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 day
