image: maven:3.8-openjdk-17

stages:
  - prepare
  - test
  - build

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  MAVEN_CLI_OPTS: "-B -ntp"
  LIBRARIES_DIR: "TourGuide/libs"
  # Liens vers les JARs sur GitLab
  GPSUTIL_JAR: "https://gitlab.com/octheoleb/gpsutil/-/raw/master/target/gpsUtil.jar"
  TRIPPRICER_JAR: "https://gitlab.com/octheoleb/trippricer/-/raw/master/target/tripPricer.jar"
  REWARDCENTRAL_JAR: "https://gitlab.com/octheoleb/rewardcentral/-/raw/master/target/RewardCentral.jar"
  GROUP_ID: "com.openclassrooms"
  VERSION: "1.0.0"
  MAVEN_REPO_URL: "https://gitlab.com/api/v4/projects/69257506/packages/maven" # URL du repository GitLab Maven

# Etape de préparation des dépendances locales
prepare-job:
  stage: prepare
  script:
    - cd $LIBRARIES_DIR
    - |
      # Installer gpsUtil
      if [ ! -f "$MAVEN_REPO_DIR/gpsUtil/gpsUtil.jar" ]; then
        mvn install:install-file \
          -Dfile=$GPSUTIL_JAR \
          -DgroupId=$GROUP_ID \
          -DartifactId=gpsUtil \
          -Dversion=$VERSION \
          -Dpackaging=jar \
          -DgeneratePom=true \
          -DrepositoryId=gitlab-maven \
          -Durl=$MAVEN_REPO_URL \
          -Dusername=$CI_JOB_TOKEN \
          $MAVEN_CLI_OPTS
      fi

      # Installer tripPricer
      if [ ! -f "$MAVEN_REPO_DIR/tripPricer/tripPricer.jar" ]; then
        mvn install:install-file \
          -Dfile=$TRIPPRICER_JAR \
          -DgroupId=$GROUP_ID \
          -DartifactId=tripPricer \
          -Dversion=$VERSION \
          -Dpackaging=jar \
          -DgeneratePom=true \
          -DrepositoryId=gitlab-maven \
          -Durl=$MAVEN_REPO_URL \
          -Dusername=$CI_JOB_TOKEN \
          $MAVEN_CLI_OPTS
      fi

      # Installer rewardCentral
      if [ ! -f "$MAVEN_REPO_DIR/rewardCentral/RewardCentral.jar" ]; then
        mvn install:install-file \
          -Dfile=$REWARDCENTRAL_JAR \
          -DgroupId=$GROUP_ID \
          -DartifactId=rewardCentral \
          -Dversion=$VERSION \
          -Dpackaging=jar \
          -DgeneratePom=true \
          -DrepositoryId=gitlab-maven \
          -Durl=$MAVEN_REPO_URL \
          -Dusername=$CI_JOB_TOKEN \
          $MAVEN_CLI_OPTS
      fi

  artifacts:
    paths:
      - .m2/repository
    expire_in: 1 hour

# Etape des tests
test-job:
  stage: test
  dependencies:
    - prepare-job
  script:
    - cd TourGuide
    - mvn test $MAVEN_CLI_OPTS
  artifacts:
    reports:
      junit: target/surefire-reports/TEST-*.xml

# Etape de build
build-job:
  stage: build
  dependencies:
    - test-job
  script:
    - cd TourGuide
    - mvn package $MAVEN_CLI_OPTS
  artifacts:
    paths:
      - TourGuide/target/*.jar
    expire_in: 1 day
